#+TITLE: Fausto's Emacs config

#+AUTHOR: Fausto Núñez Alberro
#+EMAIL: fausto.nunez@mailbox.org

#+STARTUP: indent

This is my Emacs configuration file. It's built using org-mode. GitHub can render org files and I've included a symlink README.org -> config.org so GitHub renders my config directly on the repository page.

This is a work-in-progress and I'm trying to adopt Emacs after a relatively long time using [[https://github.com/neovim/neovim][Neovim]]. Both are great projects and I'm having a difficult time abandoning either for the other, so you should check them out.

* Personal information
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Fausto Núñez Alberro")
(setq user-mail-address "fausto.nunez@mailbox.org")
#+END_SRC
* Package management
#+BEGIN_SRC emacs-lisp
(load "package")
(add-to-list 'package-archives
             '("marmalade" . "http://marmalade-repo.org/packages/"))
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)
#+END_SRC
* Set up use-package
#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)
#+END_SRC
* Theme
Set some variables to override some defaults later on
#+BEGIN_SRC emacs-lisp
(setq afternoon-background-color "#1c1c1c")
(setq visual-selected-background-color "#2c2c2c")
#+END_SRC
Initialize [[https://github.com/osener/emacs-afternoon-theme][emacs-afternoon-theme]].
#+BEGIN_SRC emacs-lisp
(use-package afternoon-theme
  :ensure t)
(load-theme 'afternoon t)
#+END_SRC
Override some theme defaults
#+BEGIN_SRC emacs-lisp
(set-face-attribute 'region nil :background visual-selected-background-color)
#+END_SRC
* Sane defaults
** Turn off menu bar
#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)
#+END_SRC
** Say y or n instead of yes or no
#+BEGIN_SRC emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC
** Emacs system customizations go on a separate file
#+BEGIN_SRC emacs-lisp
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
#+END_SRC
** Enable auto pairs
#+BEGIN_SRC emacs-lisp
(electric-pair-mode 1)
#+END_SRC
** Store all backup and autosave files in the tmp dir
#+BEGIN_SRC emacs-lisp
(defconst emacs-tmp-dir (expand-file-name (format "emacs%d" (user-uid)) temporary-file-directory))
(setq backup-directory-alist
    `((".*" . ,emacs-tmp-dir)))
(setq auto-save-file-name-transforms
    `((".*" ,emacs-tmp-dir t)))
(setq auto-save-list-file-prefix
    emacs-tmp-dir)
#+END_SRC
** Enable visual-line-mode for word wrap
#+BEGIN_SRC emacs-lisp
(global-visual-line-mode t)
#+END_SRC
** Line numbers
#+BEGIN_SRC emacs-lisp
(global-linum-mode 1)
(set-face-foreground 'linum "#555555")
(set-face-background 'linum afternoon-background-color)
(setq linum-format " %4d ")
#+END_SRC

[[https://github.com/tom-tan/hlinum-mode][hlinum-mode]] highlights the current line for linum
#+BEGIN_SRC emacs-lisp
(use-package hlinum
  :ensure t)
(set-face-foreground 'linum-highlight-face "white")
(set-face-background 'linum-highlight-face nil)
(hlinum-activate)
#+END_SRC
* Evil mode
** Reset some defaults
*** Restore default tab functionality in org-mode
#+BEGIN_SRC emacs-lisp
(setq evil-want-C-i-jump nil)
#+END_SRC
*** Restore default C-u functionality with Evil
#+BEGIN_SRC emacs-lisp
(setq evil-want-C-u-scroll t)
#+END_SRC
** Initialize Evil mode and friends
#+BEGIN_SRC emacs-lisp
(use-package evil
:ensure t
:config
(evil-mode 1)

(use-package evil-leader
:ensure t
:config
(global-evil-leader-mode))

(use-package evil-surround
:ensure t
:config
(global-evil-surround-mode))

(use-package evil-org
:ensure t
:after org
:config
(add-hook 'org-mode-hook 'evil-org-mode)
(add-hook 'evil-org-mode-hook
    (lambda ()
        (evil-org-set-key-theme))))

(use-package evil-indent-textobject
:ensure t))
#+END_SRC
** Make escape quit most things
In Delete Selection mode, if the mark is active, just deactivate it then it takes a second `keyboard-quit` to abort the minibuffer.
#+BEGIN_SRC emacs-lisp
(defun minibuffer-keyboard-quit ()
(interactive)
(if (and delete-selection-mode transient-mark-mode mark-active)
    (setq deactivate-mark  t)
(when (get-buffer "*Completions*") (delete-windows-on "*Completions*"))
(abort-recursive-edit)))

(define-key evil-normal-state-map [escape] 'keyboard-escape-quit)
(define-key evil-visual-state-map [escape] 'keyboard-quit)
(define-key minibuffer-local-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-ns-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-completion-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-must-match-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-isearch-map [escape] 'minibuffer-keyboard-quit)
#+END_SRC
** Use vim-navigator Emacs port for tmux panes
#+BEGIN_SRC emacs-lisp
(use-package navigate
:ensure t)
#+END_SRC
[[https://github.com/keith/evil-tmux-navigator][This package]] enables seamless C-[hjkl] movement through tmux panes _and_ Emacs windows. The following commands are required to be present in your tmux config:
#+BEGIN_SRC
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)n?vim(diff)?$|emacs.*$' && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)n?vim(diff)?$|emacs.*$' && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)n?vim(diff)?$|emacs.*$' && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)n?vim(diff)?$|emacs.*$' && tmux send-keys C-l) || tmux select-pane -R"
#+END_SRC
* Org-mode
#+BEGIN_SRC emacs-lisp
(setq org-startup-indented t
      org-ellipsis "  "
      org-hide-leading-stars t
      org-src-fontify-natively t
      org-pretty-entities t
      org-hide-emphasis-markers t
      org-agenda-block-separator ""
      org-fontify-whole-heading-line t
      org-fontify-done-headline t
      org-fontify-quote-and-verse-blocks t)
#+END_SRC
** Pretty bullets
#+BEGIN_SRC emacs-lisp
(use-package org-bullets
:ensure t
:config
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+END_SRC
* Helm & Projectile
#+BEGIN_SRC emacs-lisp
(use-package helm
  :ensure t
  :config (helm-mode t))
(use-package projectile
  :ensure projectile
  :config (projectile-global-mode t))
(use-package helm-projectile
  :ensure t)
(use-package helm-ag
  :ensure t)
#+END_SRC
* Other stuff
Use Emacs state in these additional modes
#+BEGIN_SRC emacs-lisp
(dolist (mode '())
(add-to-list 'evil-emacs-state-modes mode))
#+END_SRC
